name: Deploy main branch to Amazon Serverless
'on':
  push:
    branches:
      - main
env:
  AWS_REGION: ap-southeast-2
jobs:
  build-deploy-serverless:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET core sdk
        uses: actions/setup-python@v4
      - name: Setup SAM (Serverless Application Model)
        uses: aws-actions/setup-sam@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: '${{ env.AWS_REGION }}'
      - run: sam build --use-container
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
          --stack-name ashulearn-sam-python-lambda --s3-bucket vstiara-deployment-content
          --capabilities CAPABILITY_IAM --region ${{ env.AWS_REGION }}